import random from './random'

export default ()=>{
    const charades = [
       "zupa",
       "twój stary",
       "piwo",
       "szachy",
       "kefir",
       "miasto pochodzenia",
       "zielona kiełbasa",
       "student",
       "technologia",
       "scenariusz",
        "zachód",
        "torba",
        "poczucie winy",
        "żelazo",
        "rocznik",
        "golf",
        "zatrzask",
        "reżyser",
        "inteligencja",
        "płacz",
        "warzywo",
        "kuzyn",
        "wybory",
        "sprzedawca",
        "reprodukcja",
        "młotek",
        "wózek",
        "zmiana",
        "skręt",
        "formuła",
        "złapanie",
        "rozsądny",
        "dylemat",
        "wskazówka",
        "administracja",
        "ekonomia",
        "chleb",
        "restauracja",
        "kuchnia",
        "gwałt",
        "łuk",
        "koń",
        "urzędnik",
        "atmosfera",
        "olbrzym",
        "mieszkanie",
        "kierowca",
        "uczelnia",
        "dźgnięcie",
        "koniec",
        "obroża",
        "zawis",
        "bunt",
        "elektronika",
        "kierowca",
        "cios",
        "zwierzę",
        "Europa",
        "weteran",
        "przymus",
        "poduszka",
        "pałac",
        "produkcja",
        "szybkość",
        "agent",
        "wygląd",
        "utalentowany",
        "niewolnik",
        "racjonalny",
        "akcja",
        "rozwój",
        "rajd",
        "zaklęcie",
        "szkielet",
        "strażak",
        "dyskoteka",
        "namiot",
        "sukienka",
        "wiatr",
        "kościół",
        "lekcja",
        "tortury",
        "uczta",
        "rzeka",
        "ciężarówka",
        "uczeń",
        "kukurydza",
        "kolano",
        "anioł",
        "ząb",
        "panel",
        "ciasto",
        "ból",
        "wiedza",
        "lustro",
        "sól",
        "znajomy",
        "spodnie",
        "brwi",
        "dolar",
        "drewno",
        "szlachetny",
        "cud",
        "beneficjent",
        "podróż",
        "aleja",
        "pokojówka",
        "piasek",
        "bańka",
        "gra",
        "my",
        "obraz",
        "szkło",
        "materia",
        "trucizna",
        "kierunek",
        "opaska",
        "wykop",
        "czkawka",
        "bogactwo",
        "przegląd",
        "miejsce",
        "krzyk",
        "zaręczyny",
        "przyszłość",
        "jęk",
        "kupon",
        "brama",
        "bzdury",
        "firma",
        "akapit",
        "ratunek",
        "głośnik",
        "pot",
        "mąż",
        "popiół",
        "król",
        "sofa",
        "stan",
        "wykluczenie",
        "opieka",
        "wydawca",
        "trzęsienie ziemi",
        "apetyt",
        "wiersz",
        "opieka",
        "słodki",
        "próg",
        "otwarty",
        "kusza",
        "koncept",
        "więzień",
        "negatyw",
        "grosz",
        "horror",
        "mundur",
        "komplikacja",
        "nastrój",
        "handel",
        "suka",
        "późno",
        "dzwonek",
        "spojrzenie",
        "bufet",
        "sypialnia",
        "aparat",
        "pokrewieństwo",
        "równanie",
        "siła",
        "uprzedzenie",
        "montaż",
        "równość",
        "styl",
        "paradoks",
        "scena",
        "statek",
        "terminal",
        "zdobycz",
        "przyjaciel",
        "pamięć",
        "seria",
        "licznik",
        "łazienka",
        "matka",
        "sumienie",
        "dywan",
        "łąka",
        "cud",
        "cigarette",
        "broń",
        "kropka",
        "film",
        "siano",
        "nerka",
        "gotówka",
        "pochodnia",
        "wróżka",
        "mięso",
        "konkluzja",
        "uwaga",
        "moment",
        "problem",
        "rzeźba",
        "ołów",
        "siostra",
        'KLASKANIE',
        'ZIMNE PIWKO',
        'NURKOWANIE',
        'WILK MORSKI',
        'NÓŻ',
        'ĆWIKŁA',
        'KOD KRESKOWY',
        'MIŚ',
        'DAĆ KOSZA',
        'SYGNALIZACJA',
        'FAJKA WODNA',
        'SZKLANKA',
        'DUŻY BICEPS',
        'OSIOL',
        'GÓRNIK',
        'DUŻY BICEPS',
        'SHREK',
        'NASTOLATEK',
        'PIŁKA NOŻNA',
        'SCENA',
        'JAZDA NA ROLKACH',
        'CZARODZIEJKI',
        'SZKOLA',
        'PANNA MŁODA',
        'BARBIE',
        'GARNITUR',
        'BUKIET KWIATÓW',
        'WSPINACZKA',
        'KOMINIARKA',
        'AKUMULATOR',
        'TRAMWAJ',
        'WIRUSY',
        'ORKA',
        'PŁASZCZ',
        'PIANINO',
        'PIOSENKARZ',
        'SAŁATA',
        'GWÓŹDŹ',
        'PODUSZKA POWIETRZNA',
        'KOŃ',
        'NUTA',
        'JEANSY',
        'SARNA',
        'RZUT OSZCZEPEM',
        'ŚCIANA',
        'BUTELKA',
        'DOKUMENTY',
        'GANG',
        'MARATON',
        'KOMPOT',
        'IGŁA',
        'PÓJŚĆ Z TORBAMI',
        'ŁEB W ŁEB',
        'SMOK WAWELSKI',
        'WYSTĘP',
        'MUZYKA',
        'MALARZ',
        'WIELORYB',
        'KRÓLOWA ŚNIEGU',
        'MORDERCA',
        'KLAPKI',
        'EKOLOGIA',
        'KUBUŚ PUCHATEK',
        'DELFIN',
        'PIONEK',
        'LATAWIEC',
        'CHIŃCZYK',
        'KOŃ',
        'KRZYK',
        'IKONA',
        'PARTNER',
        'FRYTKI',
        'PIEKARNIK',
        'PALMA',
        'MASŁO',
        'ŚWIĘTA KROWA',
        'ŚPIEWAĆ',
        'POTOP',
        'ALICJA W KRAINIE CZARÓW',
        'WERSALKA',
        'KABARET',
        'BRZOSKWINIA',
        'NASTOLATEK',
        'KONICZYNA',
        'STOP',
        'SŁODYCZE',
        'RODZYNKI W CZEKOLADZIE',
        'SŁOIK',
        'REKOLEKCJE',
        'ŁYŻKA',
        'KONIK NA BIEGUNACH',
        'PARÓWKA',
        'SMAKOSZ',
        'OCZY',
        'NIEWIDOMY',
        'JAZDA SAMOCHODEM',
        'UBIERAĆ CHOINKĘ',
        'PAMIĘTNIK',
        'PADA ŚNIEG',
        'KOT',
        'ANAKONDA',
        'WŁADCA PIERŚCIENI',
        'PAJĄK',
        'RUSZYĆ GŁOWĄ',
        'CYRK',
        'SŁOIK',
        'DALMATYŃCZYK',
        'PRZEDSZKOLE',
        'MIŚ PANDA',
        'TRAMPKI',
        'PUDEŁKO ZAPAŁEK',
        'MAFIA',
        'PSY',
        'SER ŻÓŁTY',
        'KARABIN',
        'SOK WIELOOWOCOWY',
        'WIELKA STOPA',
        'ZUPA MLECZNA',
        'WAMPIR',
        'SZYĆ BUTY',
        'NUTA',
        'MAJTKI',
        'CHŁOP JAK DĄB',
        'PSZCZOŁA',
        'MYSZKA MICKEY',
        'GĘŚ',
        'WALENTYNKI',
        'KLIPS',
        'ŁÓŻKO PIĘTROWE',
        'POSĄG',
        'TRAMWAJ',
        'FASOLA',
        'ZIEMNIAKI',
        'CHŁOP JAK DĄB',
        'PIEPRZ I SÓL',
        'KOPYTO',
        'HUŚTAWKA',
        'PAMIĘTNIK',
        'IPOD',
        'SZOPA',
        'POLICJA',
        'PIES',
        'JEDNOROŻEC',
        'TITANIC',
        'GŁOWA MAŁA',
        'WIOSNA',
        'CHUSTECZKI HIGIENICZNE',
        'OGIEŃ',
        'EKIPA',
        'BOMBOWIEC',
        'STONOGA',
        'PSIA ŁAPKA',
        'ŚLEPA ULICZKA',
        'CZARNY ŁABĘDŹ',
        'JĘZYK CIAŁA',
        'GRANAT',
        'ŚCIANA OGNIA',
        'ORZEŁ',
        'KABANOS',
        'SŁOIK',
        'USYPIANIE DZIECKA',
        'ESKIMOS',
        'IŚĆ NA WYCIECZKĘ',
        'PAZNOKCIE',
        'STÓŁ BEZ NÓG',
        'LODÓWKA',
        'WIŚNIE',
        'UNIWERSYTET',
        'UBIERAĆ CHOINKĘ',
        'PIERNIK',
        'DYWAN',
        'ZAMRAŻARKA',
        'MIĘSO',
        'TYGRYS',
        'SKOK W DAL',
        'TYTANIC',
        'SZYNKA',
        'ZŁAMANE SERCE',
        'PANTERA',
        'GARAŻ',
        'OSIOŁ',
        'PASTA DO ZĘBÓW',
        'ZBIERANIE ODCHODÓW OD PSA',
        'STODOŁA',
        'MIŚ PANDA',
        'KARTKA',
        'SUKNIA ŚLUBNA',
        'TWARZ',
        'ZŁODZIEJ',
        'APARAT CYFROWY',
        'BIDON',
        'KOGUT',
        'BAR MLECZNY',
        'PRYSZNIC',
        'BOCIAN',
        'SŁABY PUNKT',
        'KROKIET',
        'SZKOŁA',
        'ORKIESTRA'
   ];

    return charades[random(0, charades.length-1)];
}