import random from './random'

export default ()=>{
    const charades = [
       "zupa",
       "twój stary",
       "piwo",
       "szachy",
       "kefir",
       "miasto pochodzenia",
       "zielona kiełbasa",
       "student",
       "technologia",
       "scenariusz",
        "zachód",
        "torba",
        "poczucie winy",
        "żelazo",
        "rocznik",
        "golf",
        "zatrzask",
        "reżyser",
        "inteligencja",
        "płacz",
        "warzywo",
        "kuzyn",
        "wybory",
        "sprzedawca",
        "reprodukcja",
        "młotek",
        "wózek",
        "zmiana",
        "skręt",
        "formuła",
        "złapanie",
        "rozsądny",
        "dylemat",
        "wskazówka",
        "administracja",
        "ekonomia",
        "chleb",
        "restauracja",
        "kuchnia",
        "gwałt",
        "łuk",
        "koń",
        "urzędnik",
        "atmosfera",
        "olbrzym",
        "mieszkanie",
        "kierowca",
        "uczelnia",
        "dźgnięcie",
        "koniec",
        "obroża",
        "zawis",
        "bunt",
        "elektronika",
        "kierowca",
        "cios",
        "zwierzę",
        "Europa",
        "weteran",
        "przymus",
        "poduszka",
        "pałac",
        "produkcja",
        "szybkość",
        "agent",
        "wygląd",
        "utalentowany",
        "niewolnik",
        "racjonalny",
        "akcja",
        "rozwój",
        "rajd",
        "zaklęcie",
        "szkielet",
        "strażak",
        "dyskoteka",
        "namiot",
        "sukienka",
        "wiatr",
        "kościół",
        "lekcja",
        "tortury",
        "uczta",
        "rzeka",
        "ciężarówka",
        "uczeń",
        "kukurydza",
        "kolano",
        "anioł",
        "ząb",
        "panel",
        "ciasto",
        "ból",
        "wiedza",
        "lustro",
        "sól",
        "znajomy",
        "spodnie",
        "brwi",
        "dolar",
        "drewno",
        "szlachetny",
        "cud",
        "beneficjent",
        "podróż",
        "aleja",
        "pokojówka",
        "piasek",
        "bańka",
        "gra",
        "my",
        "obraz",
        "szkło",
        "materia",
        "trucizna",
        "kierunek",
        "opaska",
        "wykop",
        "czkawka",
        "bogactwo",
        "przegląd",
        "miejsce",
        "krzyk",
        "zaręczyny",
        "przyszłość",
        "jęk",
        "kupon",
        "brama",
        "bzdury",
        "firma",
        "akapit",
        "ratunek",
        "głośnik",
        "pot",
        "mąż",
        "popiół",
        "król",
        "sofa",
        "stan",
        "wykluczenie",
        "opieka",
        "wydawca",
        "trzęsienie ziemi",
        "apetyt",
        "wiersz",
        "opieka",
        "słodki",
        "próg",
        "otwarty",
        "kusza",
        "koncept",
        "więzień",
        "negatyw",
        "grosz",
        "horror",
        "mundur",
        "komplikacja",
        "nastrój",
        "handel",
        "suka",
        "późno",
        "dzwonek",
        "spojrzenie",
        "bufet",
        "sypialnia",
        "aparat",
        "pokrewieństwo",
        "równanie",
        "siła",
        "uprzedzenie",
        "montaż",
        "równość",
        "styl",
        "paradoks",
        "scena",
        "statek",
        "terminal",
        "zdobycz",
        "przyjaciel",
        "pamięć",
        "seria",
        "licznik",
        "łazienka",
        "matka",
        "sumienie",
        "dywan",
        "łąka",
        "cud",
        "cigarette",
        "broń",
        "kropka",
        "film",
        "siano",
        "nerka",
        "gotówka",
        "pochodnia",
        "wróżka",
        "mięso",
        "konkluzja",
        "uwaga",
        "moment",
        "problem",
        "rzeźba",
        "ołów",
        "siostra",
        "kisiel",
        "nauczyciel",
        "gumisie",
        "kawa",
        "sakrament",
        "boże narodzenie",
        "biedronka",
        "kręgosłup",
        "bombowiec",
        "pyra",
        "hot dog",
        "sprzataczka",
        "samochód",
        "sms",
        "mapa",
        "wilczy głód",
        "hryzantema",
        "klucze",
        "igła",
        "dom wariatów",
        "mucha",
        "wieloryb",
        "sokole oko",
        "dzida",
        "duch",
        "święta krowa",
        "palce lizać",
        "wanna",
        "czarna róża",
        "aktor",
        "sport",
        "kapturek",
        "poziomka",
        "chłop jak dąb",
        "miotacz ognia",
        "ninja",
        "podstawówka",
        "anakonda",
        "salata",
        "lustro",
        "krasnal ogrodowy",
        "krzak",
        "ikona",
        "pantoflarz",
        "balon",
        "orzech włoski",
        "krokodyl",
        "lekcja",
        "skuter",
        "hamburger",
        "parasolka",
        "siłownia",
        "zimne piwko",
        "autyzm",
        "godzina policyjna",
        "stop",
        "golarka",
        "ziemniaki",
        "mikrofon",
        "mówić pod nosem",
        "krwawe serce",
        "dzięcioł",
        "butelka",
        "słoik",
        "oczyszczalnia scieków",
        "mama",
        "jagoda",
        "tablet",
        "ładowarka",
        "tancerz",
        "skok w bok",
        "surówka",
        "twarz",
        "słowik",
        "ekierka",
        "siodło",
        "szczerzyć zęby",
        "deszcz",
        "motyl",
        "wzdęcia",
        "serce jak dzwon",
        "ścieki",
        "boks tajski",
        "miód",
        "wisielec",
        "sylwester",
        "wakacje",
        "supermarket",
        "most linowy",
        "niania",
        "szczur",
        "spodnie w kratke",
        "policja",
        "czerwone korale",
        "sztaluga",
        "makaron",
        "teatr",
        "ręce opadają",
        "ipod",
        "minuta ciszy",
        "pianino",
        "grzyby",
        "końskie zdrowie",
        "drapacz chmur",
        "fast food",
        "robić fochy",
        "płatki z mlekiem",
        "kanapka",
        "lać wodę",
        "pisak",
        "chleb",
        "gruba książka",
        "posąg",
        "ekipa",
        "ptaszek w klatce",
        "pod kluczem",
        "prosić o rękę",
        "małe piwo",
        "choinka",
        "sztabka złota",
        "tartan",
        "ciastko z dziurką",
        "kurtyna",
        "garnek",
        "lekki chleb",
        "guzik",
        "gumka",
        "piłka plażowa",
        "kopciuszek",
        "kropla wody",
        "uczucia",
        "złodziej",
        "saneczkarstwo",
        "widelec",
        "miś uszatek",
        "śrubokręt",
        "mięso",
        "wersalka",
        "telewizor plazmowy",
        "usta",
        "sprzątanie",
        "eskimos",
        "woda gazowana",
        "wentylator",
        "pierogi ruskie",
        "reksio",
        "klapki",
        "grzybobranie",
        "gradobicie",
        "hokej",
        "rekolekcje",
        "buzia",
        "iglo",
        "czarodziejki",
        "suknia ślubna",
        "gra komputerowa",
        "wózek",
        "miś panda",
        "wieża eifla",
        "smok wawelski",
        "justin bieber",
        "sen zimowy",
        "kaczka",
        "głupawka",
        "czarna robota",
        "milczenie",
        "randka",
        "rolnik",
        "sól",
        "karuzela",
        "o wilku mowa",
        "zadzierać nosa",
        "zupa pomidorowa",
        "pies",
        "czarny łabędź",
        "napiwek",
        "apteka",
        "jedzenie",
        "psia łapka",
        "tabletki",
        "szyszka",
        "stół bez nóg",
        "wampir",
        "taniec na lodzie",
        "piekarnik",
        "psy",
        "wilk i zając",
        "meldunek",
        "telefon",
        "delfin",
        "pierogi",
        "jabłko adama",
        "znak stopu",
        "tata",
        "koniczyna",
        "ciemna masa",
        "baśnie",
        "czerwony kapturek",
        "poziomki",
        "kosić trawnik",
        "szczudła",
        "dysk twardy",
        "klaps",
        "informatyka",
        "barman",
        "biblia",
        "leniwiec",
        "krowa",
        "kaktus",
        "sok wieloowocowy",
        "kuchnia polska",
        "stół drewniany",
        "wino białe",
        "cztery ściany",
        "piosenkarz",
        "historia",
        "terminarz",
        "drink",
        "inwalida",
        "bańki mydlane",
        "biała czekolada",
        "zimowisko",
        "kosz na śmieci",
        "taksówkarz",
        "barbie",
        "jaglana kasza",
        "basen pływacki",
        "modelka",
        "marchewka",
        "głowa do góry",
        "prosić na kolanach",
        "nieme kino",
        "kula w łeb",
        "joker",
        "kalafior",
        "myszka mickey",
        "zimny prysznic",
        "helikopter w ogniu",
        "mysz komputerowa",
        "nitka",
        "godzilla",
        "studnia",
        "lalka",
        "sowie oko",
        "mumia",
        "album",
        "płatki śniegu",
        "tramwaj",
        "stonoga",
        "szczoteczka",
        "koszykówka",
        "moneta",
        "kominiarz",
        "batman",
        "okulista",
        "władca pierścieni",
        "pamiętnik",
        "pojemnik",
        "żyrafa",
        "praca",
        "podpierać ściany",
        "partner",
        "gwóźdź",
        "muszka",
        "pająk",
        "leń śmierdzący",
        "m jak miłość",
        "panda",
        "kołyska",
        "ścieżka rowerowa",
        "rzut oszczepem",
        "czapka",
        "foka",
        "krzyż na drogę",
        "zamrażarka",
        "słoń",
        "dać po nosie",
        "przedszkole",
        "prysznic",
        "urząd stanu cywilnego",
        "kogut",
        "pizza",
        "szynka",
        "złota rybka",
        "parasol",
        "cukier",
        "żaba",
        "przybić piątkę",
        "shrek",
        "szpagat",
        "czyste ręce",
        "adam małysz",
        "głuchoniemy",
        "mechanik",
        "chlew",
        "bukiet kwiatów",
        "klaskanie",
        "kosmetyczka",
        "drzewo",
        "kask motocyklowy",
        "dywan",
        "maska",
        "101 dalamtyńczyków",
        "lodówka",
        "kolumna",
        "jak dwie krople wody",
        "walentynki",
        "weterynarz",
        "ginekolog",
        "narty",
        "chińszczyzna",
        "mikser",
        "czapka z daszkiem",
        "muminki",
        "oranżada",
        "trasport",
        "banan",
        "woda mineralna",
        "huśtawka",
        "szalik",
        "porzeczka",
        "lodziarnia",
        "opakowanie",
        "paw",
        "kominiarka",
        "maraton",
        "głośniki",
        "kominek",
        "siatkówka",
        "kangur",
        "święta bożego narodzenia",
        "pianista",
        "fosa",
        "prawa ręka",
        "wigilia",
        "pokolenie",
        "stara panna",
        "lód",
        "oscypek",
        "laptop",
        "konik na biegunach",
        "paliwo",
        "krecik",
        "talerz",
        "wizytówka",
        "placki ziemniaczane",
        "słodycze",
        "dzień i noc",
        "zając",
        "mydło w płynie",
        "koszulka",
        "gruba ryba",
        "księżyc",
        "nastolatek",
        "puste koło",
        "kokos",
        "kalkulator",
        "kieł",
        "król lew",
        "krzywa",
        "ciężarówka",
        "świecąca żarówka",
        "smerfetka",
        "ściany mają uszy",
        "połknąć haczyk",
        "strażak",
        "pasażer na gapę",
        "encyklopedia",
        "cukierek",
        "chodzić po górach",
        "ser żółty",
        "wilczy apetyt",
        "kot",
        "różowe okulary",
        "bidon",
        "czekolada",
        "kartka papieru",
        "limonka",
        "język ciała",
        "język za zębami",
        "miska",
        "gargamel",
        "guma do żucia",
        "pinokio",
        "geniusz",
        "świnia",
        "głuchy jak pień",
        "krawat",
        "zmywarka",
        "pocałować klamkę",
        "piekarz",
        "zakupy",
        "moda",
        "rośliny",
        "masło",
        "kotek",
        "krzeslo",
        "kłapać dziobem",
        "pszczółka maja",
        "kotlet schabowy",
        "kuchnia",
        "kapusta",
        "kciuk w górę",
        "pingwin",
        "szyba",
        "meksykańska fala",
        "latawiec",
        "zebra",
        "fotel masujący",
        "lampion",
        "stodoła",
        "internet",
        "roleta",
        "robert kubica",
        "być w dołku",
        "gąbka",
        "detal",
        "tancerka",
        "boki zrywać",
        "pierścionek",
        "zaganianie krów",
        "avatar",
        "ciągnąć za język",
        "karmić psa",
        "wiatr",
        "park linowy",
        "wiatrak",
        "wspinaczka",
        "kroplówka",
        "płatek",
        "magazynier",
        "biologia",
        "twardy dysk",
        "czajnik",
        "las iglasty",
        "skoczek",
        "domek z kart",
        "orka",
        "kot w butach",
        "legendy",
        "licznik",
        "mycie naczyń",
        "drobny prezent",
        "wirusy",
        "meble",
        "śpiąca królewna",
        "telefon komórkowy",
        "osiol",
        "tunel",
        "morskie oko",
        "zaręczyny",
        "figurka",
        "trucht",
        "termos",
        "bilard",
        "paznokcie",
        "zegar",
        "broń",
        "struś",
        "knajpa",
        "kevin sam w domu",
        "czepek",
        "grill",
        "obraz na ścianie",
        "brzoskwinia",
        "świnka morska",
        "umywalka",
        "młoda para",
        "małpka",
        "trening",
        "duży biceps",
        "kość słoniowa",
        "żeglowanie",
        "kora",
        "snapchat",
        "skorpion",
        "abordaż",
        "zgrzytać zębami",
        "lody",
        "sekretarka",
        "komputer",
        "wielka stopa",
        "samotnik",
        "palma",
        "uniwersytet",
        "śpiewać",
        "salami",
        "jaja na twardo",
        "hasło",
        "samochód cieżarowy",
        "familiada",
        "komputer przenośny",
        "szlaban",
        "lampka nocna",
        "cukierki",
        "zabawka",
        "kula ziemska",
        "grzybica",
        "f-16",
        "miękkie nogi",
        "gazela",
        "nosić spodnie",
        "autostrada",
        "sygnalizacja",
        "łaciata krowa",
        "alarm",
        "kino",
        "herbatnik",
        "ubierać choinkę",
        "piła",
        "sanki",
        "koszule",
        "kolczyki",
        "pójść z torbami",
        "latarnia morska",
        "pieprz",
        "kompot",
        "zorza polarna",
        "księgarnia",
        "spacer w chmurach",
        "orangutan",
        "arka noego",
        "morderca",
        "czarny kot",
        "krzyk",
        "pojedynek",
        "oko w oko",
        "wąsy",
        "łóżko piętrowe",
        "egzekucja",
        "czas to pieniądz",
        "trampki",
        "parówka",
        "głos serca",
        "opera",
        "gogle narciarskie",
        "baba jaga",
        "dyrektor",
        "kurze łapki",
        "widok",
        "budka suflera",
        "oczko w głowie",
        "dron",
        "chudy jak patyk",
        "rękawiczki",
        "solarium",
        "szybki jak strzała",
        "ruchome schody",
        "szkola",
        "umywać ręce",
        "kosiarka",
        "czołówka",
        "zupa mleczna",
        "koń",
        "reklama",
        "lampard",
        "wiertarka",
        "miecz świetlny",
        "tytanic",
        "kartka",
        "demokracja",
        "sandały",
        "parada",
        "telefon stacjonarny",
        "podciąć skrzydła",
        "mleko od krowy",
        "ręcznik",
        "termometr",
        "śniadanie",
        "deskorolka",
        "skóra i kości",
        "zegar kieszonkowy",
        "wąż",
        "łeb w łeb",
        "jeść z ręki",
        "sałatka",
        "piekło",
        "czerwona gruszka",
        "warzywo",
        "kupka",
        "wyciągnąć nogi",
        "okno",
        "kręta droga",
        "pępek świata",
        "wiewiorka",
        "podwieczorek",
        "przyjaciele",
        "obrus",
        "kręcić nosem",
        "bałwan",
        "trapez",
        "łapać stopa",
        "apetyt",
        "królik",
        "święty spokój",
        "termy",
        "boisko",
        "torebka",
        "komunia",
        "budynek",
        "słaby punkt",
        "drabina",
        "mitologia",
        "obiad",
        "pasta do zębów",
        "piana mydlana",
        "ślepa uliczka",
        "sukienka",
        "sałata",
        "ugryźć się w język",
        "baton",
        "dentysta",
        "fasola",
        "gang",
        "ołówek z gumką",
        "piłka",
        "101 dalmatyńczyków",
        "basen",
        "pomidor",
        "uśpieni",
        "urząd pocztowy",
        "gepard",
        "pada śnieg",
        "pralka",
        "kartofel",
        "strzała amora",
        "film",
        "student",
        "woda zdrodlana",
        "rosół",
        "akumulator",
        "las",
        "fajka wodna",
        "piotrowska",
        "długi język",
        "hamulec",
        "osa",
        "ananas",
        "tatry",
        "tygrys",
        "scena",
        "zeus",
        "komórka",
        "niewidomy",
        "cztery kółka",
        "biały kieł",
        "wilk",
        "namiot",
        "zeszyt",
        "niedźwiedź",
        "gra karciana",
        "łańcuszek",
        "wesele",
        "karnawał",
        "szwajcarski zegarek",
        "pieróg",
        "pisanka",
        "grać na nosie",
        "głupek",
        "hipnoza",
        "narzędzia",
        "gumka do mazania",
        "western",
        "chomik",
        "doniczka",
        "sowa",
        "lokomotywa",
        "hip-hop",
        "mieć zeza",
        "co dwie glowy to nie jedna",
        "pełnia księżyca",
        "rzut dyskiem",
        "muzyka",
        "przerwa",
        "jasne jak słońce",
        "bolek i lolek",
        "mała czarna",
        "rolki",
        "płot",
        "mieszko i",
        "potop",
        "piłka nożna",
        "mieć nóż na gardle",
        "długopis",
        "plakat",
        "przytrzeć nosa",
        "poród",
        "dziki zachód",
        "toaleta",
        "turystyka",
        "samolot",
        "ogień w kominku",
        "marker",
        "monitor",
        "wiśnie",
        "super man",
        "czarna owca",
        "truskawka",
        "welon",
        "igloo",
        "przysłowie",
        "pójść do łóżka",
        "bransoletka",
        "szara myszka",
        "biurko",
        "listonosz",
        "garnitur",
        "balet",
        "filozofia",
        "kurtka",
        "klocki",
        "szkoła",
        "gotowanie",
        "pod wodą",
        "materac wodny",
        "dziubek",
        "morderstwo",
        "płetwy",
        "stokrotka",
        "majonez",
        "pan młody",
        "grawitacja",
        "dmuchany materac",
        "orzechy",
        "krasnoludek",
        "deszczówka",
        "stożek",
        "sloń",
        "kocia muzyka",
        "mama i tata",
        "orzeł",
        "osioł",
        "krokiet",
        "lilijka",
        "powietrze",
        "jazda na rolkach",
        "niebo w gębie",
        "wieżowiec",
        "romeo i julia",
        "informatyk",
        "buty",
        "motor",
        "oczy",
        "cyrk",
        "skoki narciarskie",
        "poduszka powietrzna",
        "święty mikołaj",
        "węgiel",
        "petardy",
        "dalmatyńczyk",
        "ściana ognia",
        "ogórek kiszony",
        "pieprz i sól",
        "ból głowy",
        "sympatia",
        "grzebać w nosie",
        "groszek",
        "podłoga",
        "fajerwerki",
        "żaluzje",
        "kawiarnia",
        "godzina szczytu",
        "majteczki w kropeczki",
        "iść na wycieczkę",
        "szklanka",
        "firanka",
        "kopyto",
        "brak słów",
        "bułka z masłem",
        "usypianie dziecka",
        "walizka",
        "skok w dal",
        "czołg",
        "kolorowe kwiaty",
        "zmywacz do paznokci",
        "pluszowy miś",
        "gorący kubek",
        "co łaska",
        "tulipan",
        "koszenie trawy",
        "zdrowie",
        "ufo",
        "mała syrenka",
        "biblioteczka",
        "chusteczki higieniczne",
        "film czarno-biały",
        "kocie oczy",
        "szopa",
        "żądło",
        "złamane serce",
        "majtki",
        "panieński",
        "pierścionek zaręczynowy",
        "kazimierz wielki",
        "maskotka",
        "frytki",
        "ryba",
        "ślub",
        "ciastko",
        "pudełko zapałek",
        "murarz",
        "gladiator",
        "latający dywan",
        "wiosna",
        "dać kosza",
        "gorąca głowa",
        "konik polny",
        "kłótnia",
        "bieżnia",
        "płaszcz",
        "rosołek",
        "łobuz",
        "kura domowa",
        "zapalniczka",
        "kopalnia złota",
        "jubiler",
        "wyrabianie ciasta",
        "łyżka",
        "król zwierząt",
        "korkociąg",
        "latarka",
        "nurek",
        "zły pies",
        "marynarka",
        "rower",
        "książka kucharska",
        "flaming",
        "piaskownica",
        "pokemon",
        "komluter",
        "radiowóz",
        "zmierzch",
        "marchew",
        "wf",
        "zabawki",
        "kod kreskowy",
        "młotek",
        "droga mleczna",
        "jazda samochodem",
        "nadstawiać uszu",
        "smoking",
        "ośmiornica",
        "pantera",
        "emerytura",
        "terminator",
        "pustka",
        "chińczyk",
        "sushi",
        "przestraszyć kogoś",
        "naleśniki",
        "zlewozmywak",
        "hipopotam",
        "schody ruchome",
        "melanż",
        "woda",
        "malina",
        "błoto",
        "agrafka",
        "spodnie",
        "zbieranie odchodów od psa",
        "spinacz biurowy",
        "bar mleczny",
        "szczoteczka do zębów",
        "iluzjonista",
        "jeansy",
        "głęboka woda",
        "mikroskop",
        "królowa śniegu",
        "klamka",
        "koziołek matołek",
        "satelita",
        "łóżko",
        "siedzieć po turecku",
        "policjant",
        "tornister",
        "sztorm",
        "woda utleniona",
        "wielbłąd",
        "orzech",
        "garaż",
        "borówka",
        "występ",
        "rwać włosy z głowy",
        "sieć",
        "zabawa w piasku",
        "chemia",
        "kakao",
        "pszczoła",
        "kobieta",
        "ćwikła",
        "nosorożec",
        "padać z nóg",
        "klej",
        "bombka choinkowa",
        "autokar",
        "kopiec kreta",
        "bocian",
        "pogoda",
        "fryzura",
        "patelnia",
        "silny jak byk",
        "wulkan",
        "brukowiec",
        "alicja w krainie czarów",
        "lew",
        "małpa",
        "jemioła",
        "padać na kolana",
        "titanic",
        "paluch",
        "terapia",
        "okulary przeciwsłoneczne",
        "taśma klejąca",
        "kurnik",
        "gra słów",
        "gry hazardowe",
        "pobocze",
        "rodzynki w czekoladzie",
        "drugie śniadanie",
        "cytryna",
        "sklep monopolowy",
        "miękkie lądowanie",
        "kombinezon",
        "papryka",
        "ogień",
        "droga krzyżowa",
        "gra planszowa",
        "poduszka",
        "żarówka",
        "kolacja",
        "ognisko",
        "sztylet",
        "półka",
        "mafia",
        "kolędnicy",
        "karmel",
        "buty sportowe",
        "ciąża",
        "mądrala",
        "orkiestra",
        "rzygać jak kot",
        "bandyta",
        "śliwka",
        "karate",
        "piszczel",
        "kobieta w ciąży",
        "pilot",
        "mała ściąga",
        "przepis",
        "nóż",
        "pokaz mody",
        "pionek",
        "górnik",
        "mazak",
        "zamek z piasku",
        "głuchy telefon",
        "bajka",
        "klapki na oczach",
        "papuga",
        "komoda",
        "kultura",
        "chirurg",
        "wilkołak",
        "spowiedź",
        "aparat cyfrowy",
        "asystentka",
        "kubuś puchatek",
        "głowa mała",
        "ojciec chrzestny",
        "karimata",
        "nuta",
        "pudełko",
        "prawo jazdy",
        "obcy",
        "blady jak ściana",
        "kabaret",
        "broda",
        "jedwab",
        "wisieć na telefonie",
        "lekarz rodzinny",
        "malarz",
        "tom i jerry",
        "dzban z wodą",
        "łagodny jak baranek",
        "jadłospis",
        "popcorn",
        "druga strona medalu",
        "krzesło",
        "gra w butelkę",
        "jazda na rowerze",
        "jednorożec",
        "fryzjer",
        "sadysta",
        "mikstura",
        "kabanos",
        "pięta achillesa",
        "spacer z psem",
        "ruszyć głową",
        "ołówek",
        "onomatopeja",
        "godzina duchów",
        "łyżwy",
        "gęsia skórka",
        "mleko",
        "lekarz",
        "żyletka",
        "śmiać się do łez",
        "grabarz",
        "cukiernik",
        "duży ekran",
        "nurkowanie",
        "kapela",
        "indyk",
        "rymowanka",
        "kucharka",
        "głodny jak wilk",
        "smakosz",
        "boa dusiciel",
        "panna młoda",
        "wilk morski",
        "pluszak",
        "dostać baty",
        "obcinanie",
        "puścić bąka",
        "kurzajka",
        "dowód rejestracyjny",
        "strzykawka",
        "gruby jak beczka",
        "gruba baba",
        "coca-cola",
        "winogrono",
        "na zdrowie",
        "fabryka",
        "kurza stopa",
        "koń wyścigowy",
        "broszka",
        "koszula",
        "kromka chleba",
        "wychowanie fizyczne",
        "telewizor",
        "kamizelka",
        "papier toaletowy",
        "gęś",
        "sarna",
        "stać w miejscu",
   ];

    return charades[random(0, charades.length-1)];
}